spring:
  application:
    name: eureka-client
server:
  port: 2025
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
      instance:
      preferIpAddress: true
